### ISSUE TITLE
no work

### ISSUE THREAD

**Issue by UnChaotic** [shockpast/leysourceengineclient#2]
![image](https://github.com/shockpast/leysourceengineclient/assets/40539855/1af25086-06b1-4fd4-ad85-2ba4b1532a8f)

**Comment by shockpast** [comment]
LeySourceEngineClient supports only Garry's Mod afaik.

Do you have space in the end of `steam_appid.txt` that is in the same folder as client? If not, then you should put it right away, I didn't have time to fix it, but that might be issue, otherwise I don't know why is server returning this error.

**Comment by UnChaotic** [comment]
You got 

> LeySourceEngineClient supports only Garry's Mod afaik.
> 
> Do you have space in the end of `steam_appid.txt` that is in the same folder as client? If not, then you should put it right away, I didn't have time to fix it, but that might be issue, otherwise I don't know why is server returning this error.

that fixed, you got discord? i wanna talk to you
